#!/bin/bash
set -e

# ── Friendly output helpers ──────────────────────────────────────────────
BOLD='\033[1m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; RESET='\033[0m'
step()    { echo -e "\n${BOLD}${YELLOW}==> $1${RESET}"; }
info()    { echo "    $1"; }
success() { echo -e "${GREEN}✔ $1${RESET}"; }
fail()    { echo -e "${RED}✘ $1${RESET}"; exit 1; }

echo -e "${BOLD}=================================================================="
echo "  DevOps App - Kubernetes Deployment"
echo "  This will: apply Terraform (RDS/S3/SNS), create or reuse an EKS"
echo "  cluster, build & push images, and deploy the app to Kubernetes."
echo "  Total time: ~15-25 minutes on a first run (mostly EKS cluster boot)."
echo -e "==================================================================${RESET}"

step "[0/8] Running pre-flight checks..."

info "Checking required CLI tools..."
for tool in terraform eksctl aws kubectl docker; do
    command -v "$tool" >/dev/null 2>&1 || fail "'$tool' is not installed or not on your PATH. Install it and re-run this script."
done
success "terraform, eksctl, aws, kubectl, docker all found."

info "Checking Docker is actually running..."
docker info >/dev/null 2>&1 \
    || fail "Docker is installed but the daemon isn't running. Start Docker Desktop (or the docker service) and try again."
success "Docker daemon is reachable."

info "Checking AWS credentials..."
export AWS_REGION="us-east-1"
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text) \
    || fail "Could not reach AWS. Run 'aws configure' first and make sure your credentials are valid."
export AWS_ACCOUNT_ID
CLUSTER_NAME="devops-cluster"
success "Authenticated to AWS account $AWS_ACCOUNT_ID."

info "Checking terraform.tfvars..."
if [ ! -f terraform/terraform.tfvars ]; then
    info "Not found - creating it now (asked once; only non-sensitive values are stored here)."
    set +e
    while true; do
        read -p "    S3 bucket name prefix (lowercase letters/numbers/hyphens, 3-63 chars): " BUCKET_NAME
        [[ "$BUCKET_NAME" =~ ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$ ]] && break
        echo -e "${RED}    Invalid - lowercase letters, numbers, hyphens only, 3-63 characters.${RESET}"
    done
    read -p "    Email address for SNS alerts: " MY_EMAIL
    set -e
    cat <<EOF > terraform/terraform.tfvars
# Auto-generated by setup.sh - non-sensitive values only.
# db_password is handled separately and is NEVER written to this file.
# teardown.sh deletes this file automatically; setup.sh recreates it on the next run.
bucket_name = "${BUCKET_NAME}"
my_email    = "${MY_EMAIL}"
EOF
    success "terraform/terraform.tfvars created."
else
    success "terraform.tfvars already exists, reusing it."
fi
# db_password must never be persisted to disk - if an older tfvars file still has
# it (e.g. hand-edited), strip it so the fresh prompt below (via TF_VAR_db_password)
# is what actually gets used.
if grep -q '^db_password' terraform/terraform.tfvars 2>/dev/null; then
    sed -i '/^db_password/d' terraform/terraform.tfvars
    info "Removed db_password from terraform.tfvars - it's supplied securely below instead, never stored on disk."
fi

info "Checking the EC2 key pair Terraform will need..."
KEY_NAME=$(grep -E '^\s*key_name\s*=' terraform/terraform.tfvars 2>/dev/null | sed -E 's/^[^=]*=\s*"([^"]*)".*/\1/')
KEY_NAME="${KEY_NAME:-devops-project-key}"
aws ec2 describe-key-pairs --key-names "$KEY_NAME" --region "$AWS_REGION" >/dev/null 2>&1 \
    || fail "EC2 key pair '$KEY_NAME' not found in $AWS_REGION - Terraform needs it to exist first.\n   Create it with:\n   aws ec2 create-key-pair --key-name $KEY_NAME --region $AWS_REGION --query 'KeyMaterial' --output text > ~/.ssh/$KEY_NAME.pem && chmod 400 ~/.ssh/$KEY_NAME.pem"
success "EC2 key pair '$KEY_NAME' exists."

step "[1/8] Enter secrets for this run (kept in memory only, never written to disk)"
set +e
while true; do
    read -s -p "    Database password (min 8 characters): " DB_PASSWORD; echo
    read -s -p "    Confirm database password: " DB_PASSWORD_CONFIRM; echo
    [ "$DB_PASSWORD" = "$DB_PASSWORD_CONFIRM" ] || { echo -e "${RED}    Passwords did not match, try again.${RESET}"; continue; }
    [ ${#DB_PASSWORD} -ge 8 ] || { echo -e "${RED}    Must be at least 8 characters (RDS requirement), try again.${RESET}"; continue; }
    break
done
read -p    "    AWS Access Key ID (app's S3/SNS access):     " AWS_ACCESS_KEY
read -s -p "    AWS Secret Access Key: " AWS_SECRET_KEY; echo
set -e
export TF_VAR_db_password="$DB_PASSWORD"
success "Secrets captured for this run."

step "[2/8] Applying Terraform (RDS, S3, SNS, IAM, networking)..."
cd terraform
terraform init -input=false
# -auto-approve: this script already stops (set -e) on any Terraform error,
# and re-running apply on unchanged infra is a safe no-op, so we skip the
# interactive "yes" prompt to keep the whole deploy hands-off.
terraform apply -auto-approve
VPC_ID=$(terraform output -raw vpc_id)
PUBLIC_SUBNET_IDS=$(terraform output -raw public_subnet_ids)
PRIVATE_SUBNET_IDS=$(terraform output -raw private_subnet_ids)
RDS_SG_ID=$(terraform output -raw rds_security_group_id)
RDS_ENDPOINT_FULL=$(terraform output -raw rds_endpoint)
DB_HOST=$(echo $RDS_ENDPOINT_FULL | cut -d':' -f1)
S3_BUCKET=$(terraform output -raw s3_bucket_name)
SNS_TOPIC=$(terraform output -raw sns_topic_arn)
DB_NAME=$(terraform output -raw db_name 2>/dev/null || echo "appdb")
cd ..
success "AWS infrastructure ready (RDS: $DB_HOST)."

PENDING_EMAIL=$(aws sns list-subscriptions-by-topic --topic-arn "$SNS_TOPIC" --region "$AWS_REGION" \
    --query "Subscriptions[?SubscriptionArn=='PendingConfirmation'].Endpoint" --output text 2>/dev/null || true)
if [ -n "$PENDING_EMAIL" ]; then
    echo -e "${YELLOW}    ⚠ SNS email ($PENDING_EMAIL) hasn't been confirmed yet.${RESET}"
    echo "      Check that inbox and click the confirmation link, or alert emails won't arrive"
    echo "      (the app will still work and report success either way)."
fi

step "[3/8] Ensuring EKS cluster '$CLUSTER_NAME' exists inside VPC $VPC_ID..."
if eksctl get cluster --name "$CLUSTER_NAME" --region "$AWS_REGION" >/dev/null 2>&1; then
    info "Cluster already exists, reusing it."
else
    info "Creating cluster inside the existing VPC/subnets (this takes 15-20 minutes)..."
    eksctl create cluster \
        --name "$CLUSTER_NAME" \
        --region "$AWS_REGION" \
        --vpc-public-subnets="$PUBLIC_SUBNET_IDS" \
        --vpc-private-subnets="$PRIVATE_SUBNET_IDS" \
        --nodes 2 \
        --node-type t3.small \
        --managed
fi
aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_REGION"
success "kubectl is now pointed at '$CLUSTER_NAME'."

step "[4/8] Allowing the EKS cluster to reach RDS on port 5432..."
EKS_SG_ID=$(aws eks describe-cluster --name "$CLUSTER_NAME" --region "$AWS_REGION" \
    --query 'cluster.resourcesVpcConfig.clusterSecurityGroupId' --output text)
aws ec2 authorize-security-group-ingress \
    --group-id "$RDS_SG_ID" \
    --protocol tcp --port 5432 \
    --source-group "$EKS_SG_ID" \
    --region "$AWS_REGION" 2>/dev/null && success "Firewall rule added." \
    || info "Rule already exists, skipping."

step "[5/8] Writing the Kubernetes ConfigMap..."
cat <<EOF > k8s/01-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: devops-app
data:
  DB_HOST: "${DB_HOST}"
  DB_PORT: "5432"
  DB_NAME: "${DB_NAME}"
  DB_USER: "postgres"
  S3_BUCKET_NAME: "${S3_BUCKET}"
  SNS_TOPIC_ARN: "${SNS_TOPIC}"
  AWS_REGION: "${AWS_REGION}"
  POLL_INTERVAL_SECONDS: "30"
EOF
success "k8s/01-configmap.yaml written."

step "[6/8] Writing the Kubernetes Secret (reusing the credentials from step 1)..."
B64_DB_PASS=$(echo -n "$DB_PASSWORD" | base64 | tr -d '\n')
B64_AWS_KEY=$(echo -n "$AWS_ACCESS_KEY" | base64 | tr -d '\n')
B64_AWS_SECRET=$(echo -n "$AWS_SECRET_KEY" | base64 | tr -d '\n')

cat <<EOF > k8s/02-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-app
type: Opaque
data:
  DB_PASSWORD: ${B64_DB_PASS}
  AWS_ACCESS_KEY_ID: ${B64_AWS_KEY}
  AWS_SECRET_ACCESS_KEY: ${B64_AWS_SECRET}
EOF
success "k8s/02-secret.yaml written (git-ignored, never commit this file)."

step "[7/8] Building, tagging, and pushing Docker images to ECR..."
aws ecr get-login-password --region "$AWS_REGION" | \
    docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com" >/dev/null
for service in frontend backend worker; do
    info "Processing $service..."
    docker build -q -t devops-$service ./$service
    docker tag devops-$service:latest "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/devops-$service:v1.0.0"
    docker push -q "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/devops-$service:v1.0.0" >/dev/null
done
success "All 3 images pushed as :v1.0.0."

step "[8/8] Deploying to Kubernetes and waiting for rollout..."
# Applied as an explicit, dependency-ordered list rather than `kubectl apply -f k8s/`
# on the whole directory - k8s/02-secret.example.yaml defines a Secret with the same
# name as k8s/02-secret.yaml (the real one), and applying both is order-dependent:
# whichever gets applied last silently wins with its placeholder values.
kubectl apply -f k8s/00-namespace.yaml
kubectl apply -f k8s/00-serviceaccount.yaml
kubectl apply -f k8s/01-configmap.yaml
kubectl apply -f k8s/02-secret.yaml
kubectl apply -f k8s/03-deployments.yaml
kubectl apply -f k8s/04-services.yaml
kubectl apply -f k8s/05-network-policies.yaml
kubectl rollout status deployment/frontend-deployment -n devops-app --timeout=180s
kubectl rollout status deployment/backend-deployment -n devops-app --timeout=180s
kubectl rollout status deployment/worker-deployment -n devops-app --timeout=180s
success "All deployments are healthy."

info "Waiting for AWS to provision the Load Balancer URL (usually under a minute)..."
EXTERNAL_IP=""
while [ -z "$EXTERNAL_IP" ]; do
  sleep 5
  EXTERNAL_IP=$(kubectl get svc frontend-service -n devops-app --template="{{range .status.loadBalancer.ingress}}{{.hostname}}{{end}}")
done

echo -e "\n${GREEN}${BOLD}=================================================================="
echo "  DEPLOYMENT COMPLETE"
echo "==================================================================${RESET}"
echo "  App URL:        http://$EXTERNAL_IP"
echo "  Check pods:      kubectl get pods -n devops-app"
echo "  Check services:  kubectl get svc -n devops-app"
echo "  Tail logs:       kubectl logs -f deployment/backend-deployment -n devops-app"
echo "  Tear everything down when you're done: make k8s-teardown"
echo -e "${GREEN}${BOLD}==================================================================${RESET}"
