#!/bin/bash
set -e

# output helpers
BOLD='\033[1m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; RESET='\033[0m'
step()    { echo -e "\n${BOLD}${YELLOW}==> $1${RESET}"; }
info()    { echo "    $1"; }
success() { echo -e "${GREEN}✔ $1${RESET}"; }
fail()    { echo -e "${RED}✘ $1${RESET}"; exit 1; }

echo -e "${BOLD}=================================================================="
echo "  DevOps App - Kubernetes Deployment"
echo "  This will: apply Terraform (RDS/S3/SNS), create or reuse an EKS"
echo "  cluster, build & push images, install ArgoCD, and deploy the app"
echo "  via GitOps (ArgoCD watching this repo's Helm chart)."
echo "  Total time: ~20-30 minutes on a first run (mostly EKS cluster boot)."
echo -e "==================================================================${RESET}"

step "[0/8] Running pre-flight checks..."

info "Checking required CLI tools..."

# aws and docker are never auto-installed: aws-cli is often already managed
# inside a venv (pip install awscli), and docker is usually Docker Desktop,
# a GUI installer this script can't drive.
for tool in aws docker; do
    command -v "$tool" >/dev/null 2>&1 \
        || fail "'$tool' is not installed or not on your PATH. Install it yourself and re-run this script."
done

install_terraform() {
    wget -qO- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg >/dev/null
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
        | sudo tee /etc/apt/sources.list.d/hashicorp.list >/dev/null
    sudo apt-get update -qq && sudo apt-get install -y terraform
}
install_kubectl() {
    local ver; ver=$(curl -L -s https://dl.k8s.io/release/stable.txt)
    curl -fsSL -o /tmp/kubectl "https://dl.k8s.io/release/${ver}/bin/linux/amd64/kubectl"
    chmod +x /tmp/kubectl
    sudo mv /tmp/kubectl /usr/local/bin/kubectl
}
install_eksctl() {
    curl -fsSL -o /tmp/eksctl.tar.gz "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz"
    tar -xzf /tmp/eksctl.tar.gz -C /tmp && rm -f /tmp/eksctl.tar.gz
    sudo mv /tmp/eksctl /usr/local/bin/eksctl
}
install_helm() {
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
}

# terraform/eksctl/kubectl/helm are plain binaries with no venv-conflict risk,
# so offering to install them is safe - but still asked one at a time, never
# silent, since each one runs real sudo commands against the system.
for tool in terraform eksctl kubectl helm; do
    command -v "$tool" >/dev/null 2>&1 && continue
    echo -e "${YELLOW}    '$tool' is not installed.${RESET}"
    set +e
    read -p "    Install it now automatically? [y/N]: " REPLY
    set -e
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
        info "Installing $tool..."
        "install_$tool"
        command -v "$tool" >/dev/null 2>&1 || fail "Automatic install of '$tool' did not succeed - install it manually and re-run."
        success "$tool installed."
    else
        fail "'$tool' is required. Install it manually and re-run this script."
    fi
done
success "terraform, eksctl, aws, kubectl, helm, docker all found."

info "Checking Docker is actually running..."
docker info >/dev/null 2>&1 \
    || fail "Docker is installed but the daemon isn't running. Start Docker Desktop (or the docker service) and try again."
success "Docker daemon is reachable."

info "Checking AWS credentials..."
export AWS_REGION="us-east-1"
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text) \
    || fail "Could not reach AWS. Run 'aws configure' first and make sure your credentials are valid."
export AWS_ACCOUNT_ID
CLUSTER_NAME="devops-cluster"
success "Authenticated to AWS account $AWS_ACCOUNT_ID."

info "Checking terraform.tfvars..."
if [ ! -f terraform/terraform.tfvars ]; then
    info "Not found - creating it now (asked once; only non-sensitive values are stored here)."
    set +e
    while true; do
        read -p "    S3 bucket name prefix (lowercase letters/numbers/hyphens, 3-63 chars): " BUCKET_NAME
        [[ "$BUCKET_NAME" =~ ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$ ]] && break
        echo -e "${RED}    Invalid - lowercase letters, numbers, hyphens only, 3-63 characters.${RESET}"
    done
    read -p "    Email address for SNS alerts: " MY_EMAIL
    set -e
    cat <<EOF > terraform/terraform.tfvars
# Auto-generated by setup.sh - non-sensitive values only.
# db_password is handled separately and is NEVER written to this file.
# teardown.sh deletes this file automatically; setup.sh recreates it on the next run.
bucket_name = "${BUCKET_NAME}"
my_email    = "${MY_EMAIL}"
EOF
    success "terraform/terraform.tfvars created."
else
    success "terraform.tfvars already exists, reusing it."
fi
# db_password must never be persisted to disk - if an older tfvars file still has
# it (e.g. hand-edited), strip it so the fresh prompt below (via TF_VAR_db_password)
# is what actually gets used.
if grep -q '^db_password' terraform/terraform.tfvars 2>/dev/null; then
    sed -i '/^db_password/d' terraform/terraform.tfvars
    info "Removed db_password from terraform.tfvars - it's supplied securely below instead, never stored on disk."
fi

step "[1/8] Enter the database password for this run (kept in memory only, never written to disk)"
# No AWS Access Key / Secret prompt anymore - backend-sa and worker-sa get AWS
# permissions via IRSA (step 5) instead of long-lived static credentials.
set +e
while true; do
    read -s -p "    Database password (min 8 characters): " DB_PASSWORD; echo
    read -s -p "    Confirm database password: " DB_PASSWORD_CONFIRM; echo
    [ "$DB_PASSWORD" = "$DB_PASSWORD_CONFIRM" ] || { echo -e "${RED}    Passwords did not match, try again.${RESET}"; continue; }
    [ ${#DB_PASSWORD} -ge 8 ] || { echo -e "${RED}    Must be at least 8 characters (RDS requirement), try again.${RESET}"; continue; }
    break
done
set -e
export TF_VAR_db_password="$DB_PASSWORD"
success "Database password captured for this run."

step "[2/8] Applying Terraform (RDS, S3, SNS, IAM, networking)..."
cd terraform
terraform init -input=false
# -auto-approve: this script already stops (set -e) on any Terraform error,
# and re-running apply on unchanged infra is a safe no-op, so we skip the
# interactive "yes" prompt to keep the whole deploy hands-off.
terraform apply -auto-approve
VPC_ID=$(terraform output -raw vpc_id)
PUBLIC_SUBNET_IDS=$(terraform output -raw public_subnet_ids)
PRIVATE_SUBNET_IDS=$(terraform output -raw private_subnet_ids)
RDS_SG_ID=$(terraform output -raw rds_security_group_id)
RDS_ENDPOINT_FULL=$(terraform output -raw rds_endpoint)
DB_HOST=$(echo $RDS_ENDPOINT_FULL | cut -d':' -f1)
S3_BUCKET=$(terraform output -raw s3_bucket_name)
SNS_TOPIC=$(terraform output -raw sns_topic_arn)
DB_NAME=$(terraform output -raw db_name 2>/dev/null || echo "appdb")
cd ..
success "AWS infrastructure ready (RDS: $DB_HOST)."

PENDING_EMAIL=$(aws sns list-subscriptions-by-topic --topic-arn "$SNS_TOPIC" --region "$AWS_REGION" \
    --query "Subscriptions[?SubscriptionArn=='PendingConfirmation'].Endpoint" --output text 2>/dev/null || true)
if [ -n "$PENDING_EMAIL" ]; then
    echo -e "${YELLOW}    ⚠ SNS email ($PENDING_EMAIL) hasn't been confirmed yet.${RESET}"
    echo "      Check that inbox and click the confirmation link, or alert emails won't arrive"
    echo "      (the app will still work and report success either way)."
fi

step "[3/8] Ensuring EKS cluster '$CLUSTER_NAME' exists inside VPC $VPC_ID..."
if eksctl get cluster --name "$CLUSTER_NAME" --region "$AWS_REGION" >/dev/null 2>&1; then
    info "Cluster already exists, reusing it."
else
    info "Creating cluster inside the existing VPC/subnets (this takes 15-20 minutes)..."
    # 3 nodes, not 2: t3.small's pod ceiling is set by its network interfaces'
    # IP capacity (EKS/VPC CNI), not CPU/memory - 11 pods/node regardless of
    # how much compute is actually free. With kube-system, CoreDNS, ArgoCD,
    # cert-manager, and this app all scheduled, 2 nodes (22 slots) isn't
    # enough headroom; 3 nodes (33 slots) is, for a small added cost.
    eksctl create cluster \
        --name "$CLUSTER_NAME" \
        --region "$AWS_REGION" \
        --vpc-public-subnets="$PUBLIC_SUBNET_IDS" \
        --vpc-private-subnets="$PRIVATE_SUBNET_IDS" \
        --nodes 3 \
        --node-type t3.small \
        --managed
fi
aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_REGION"
success "kubectl is now pointed at '$CLUSTER_NAME'."

step "[4/8] Allowing the EKS cluster to reach RDS on port 5432..."
EKS_SG_ID=$(aws eks describe-cluster --name "$CLUSTER_NAME" --region "$AWS_REGION" \
    --query 'cluster.resourcesVpcConfig.clusterSecurityGroupId' --output text)
aws ec2 authorize-security-group-ingress \
    --group-id "$RDS_SG_ID" \
    --protocol tcp --port 5432 \
    --source-group "$EKS_SG_ID" \
    --region "$AWS_REGION" 2>/dev/null && success "Firewall rule added." \
    || info "Rule already exists, skipping."

step "[5/8] Setting up IRSA so backend/worker get AWS access without static keys..."
# IRSA lets a pod assume an IAM role via a short-lived token instead of a
# long-lived access key in a Secret. Needs an OIDC provider on the cluster
# plus a role per ServiceAccount, trusted only by that SA, using the same
# least-privilege policy from terraform/iam.tf. frontend-sa gets no role -
# it never talks to AWS.
# The namespace is templated in the chart (helm/devops-app/templates/namespace.yaml)
# rather than created as a one-off raw manifest, so it stays defined in one place.
# It still has to exist now, before ArgoCD ever runs: eksctl needs somewhere to
# put backend-sa/worker-sa. Rendering just that one template keeps this in sync
# with the chart instead of duplicating the Namespace definition here.
helm template devops-app ./helm/devops-app --namespace devops-app \
    --show-only templates/namespace.yaml | kubectl apply -f -

eksctl utils associate-iam-oidc-provider \
    --cluster "$CLUSTER_NAME" --region "$AWS_REGION" --approve
success "Cluster has an OIDC provider (required for IRSA)."

POLICY_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:policy/DevOps-App-Least-Privilege-Policy"
for sa in backend-sa worker-sa; do
    eksctl create iamserviceaccount \
        --cluster "$CLUSTER_NAME" --region "$AWS_REGION" \
        --namespace devops-app --name "$sa" \
        --attach-policy-arn "$POLICY_ARN" \
        --approve --override-existing-serviceaccounts
    success "$sa can now reach S3/SNS via IRSA - no AWS keys involved."
done

step "[6/8] Installing cert-manager and creating a self-signed TLS issuer..."
# cert-manager issues and auto-renews the frontend's cert instead of a one-off
# openssl script. Still self-signed - there's no domain pointed at the load
# balancer to get a real CA-trusted cert from - but now issued and rotated
# the way a production cert-manager + Let's Encrypt setup would work, just
# with a SelfSigned issuer instead of an ACME one.
if ! kubectl get deployment cert-manager -n cert-manager >/dev/null 2>&1; then
    info "Installing cert-manager (first run only)..."
    # --server-side: same reason as ArgoCD below - cert-manager's CRDs are
    # too large for client-side apply's last-applied-configuration annotation.
    kubectl apply --server-side --force-conflicts \
        -f https://github.com/cert-manager/cert-manager/releases/download/v1.16.2/cert-manager.yaml >/dev/null
else
    info "cert-manager already installed, reusing it."
fi
kubectl rollout status deployment/cert-manager -n cert-manager --timeout=180s
kubectl rollout status deployment/cert-manager-webhook -n cert-manager --timeout=180s
kubectl rollout status deployment/cert-manager-cainjector -n cert-manager --timeout=180s
success "cert-manager is ready."

# The webhook can take a few seconds to finish its own TLS bootstrap after its
# Deployment reports ready, so this is retried instead of failing the whole
# deploy over a transient timing issue.
CLUSTERISSUER=$(mktemp)
cat <<EOF > "$CLUSTERISSUER"
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
EOF
ISSUER_READY=false
for i in 1 2 3 4 5; do
    kubectl apply -f "$CLUSTERISSUER" >/dev/null 2>&1 && { ISSUER_READY=true; break; }
    sleep 5
done
rm -f "$CLUSTERISSUER"
[ "$ISSUER_READY" = true ] || fail "Could not create the ClusterIssuer after 5 attempts - check 'kubectl get pods -n cert-manager'."
success "Self-signed ClusterIssuer ready."

B64_DB_PASS=$(echo -n "$DB_PASSWORD" | base64 | tr -d '\n')

step "[7/8] Building, scanning, tagging, and pushing Docker images to ECR..."
aws ecr get-login-password --region "$AWS_REGION" | \
    docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com" >/dev/null

# Trivy is optional (bonus, not one of the hard-required tools from step 0) -
# scan if it's available, skip quietly if not.
HAVE_TRIVY=false
if command -v trivy >/dev/null 2>&1; then
    HAVE_TRIVY=true
else
    info "trivy not installed - skipping image vulnerability scanning (optional)."
    info "Install: https://aquasecurity.github.io/trivy/latest/getting-started/installation/"
fi

for service in frontend backend worker; do
    info "Processing $service..."
    docker build -q -t devops-$service ./$service

    if [ "$HAVE_TRIVY" = true ]; then
        info "Scanning devops-$service for HIGH/CRITICAL vulnerabilities..."
        # --exit-code 0: report findings but never fail the deploy over them -
        # base images like python:3.11-slim will always have some OS-level CVEs
        # that aren't practically fixable from this project alone.
        trivy image --severity HIGH,CRITICAL --quiet --exit-code 0 --table-mode summary devops-$service:latest
    fi

    docker tag devops-$service:latest "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/devops-$service:v1.0.0"
    docker push -q "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/devops-$service:v1.0.0" >/dev/null
done
success "All 3 images built, scanned, and pushed as :v1.0.0."

step "[8/8] Installing ArgoCD and deploying via GitOps..."
# From here on the app is kept in sync by ArgoCD watching this repo, not by a
# direct `helm upgrade` call. Push a chart change to git (or wait for ArgoCD's
# poll cycle) and it reconciles the cluster to match; selfHeal also reverts
# any manual kubectl edit back to what's in git.
REPO_URL="https://github.com/MaxTsyganov/Running_Devops_Project.git"
REPO_BRANCH="main"

if ! kubectl get deployment argocd-server -n argocd >/dev/null 2>&1; then
    info "Installing ArgoCD (first run only - this takes a couple of minutes)..."
    # Checking the deployment, not just the namespace, keeps this idempotent
    # even after a previous run failed partway through the install.
    kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f - >/dev/null
    # --server-side: plain `kubectl apply` stores the whole manifest in an
    # annotation for diffing, and ArgoCD's CRDs are big enough to blow past
    # etcd's 256KB annotation limit. Server-side apply avoids that annotation.
    kubectl apply -n argocd --server-side --force-conflicts \
        -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml >/dev/null
else
    info "ArgoCD already installed, reusing it."
fi
kubectl rollout status statefulset/argocd-application-controller -n argocd --timeout=180s
kubectl rollout status deployment/argocd-server -n argocd --timeout=180s
success "ArgoCD is ready."

# Dynamic values (RDS host, S3/SNS names, password, TLS cert) can't live in
# git, so they're embedded straight into this Application object instead,
# generated fresh here and applied via kubectl - never committed. ArgoCD
# only reads the chart templates from git.
ARGOCD_APP=$(mktemp)
cat <<EOF > "$ARGOCD_APP"
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ${REPO_URL}
    targetRevision: ${REPO_BRANCH}
    path: helm/devops-app
    helm:
      valuesObject:
        image:
          registry: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
        config:
          dbHost: "${DB_HOST}"
          s3BucketName: "${S3_BUCKET}"
          snsTopicArn: "${SNS_TOPIC}"
        secrets:
          dbPasswordB64: "${B64_DB_PASS}"
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
EOF
kubectl apply -f "$ARGOCD_APP"
rm -f "$ARGOCD_APP"
success "ArgoCD Application created - watching $REPO_URL ($REPO_BRANCH) at helm/devops-app."

info "Waiting for ArgoCD to sync (first sync of a new Application is usually quick)..."
WAITED=0
while true; do
    SYNC=$(kubectl get application devops-app -n argocd -o jsonpath='{.status.sync.status}' 2>/dev/null || echo "")
    HEALTH=$(kubectl get application devops-app -n argocd -o jsonpath='{.status.health.status}' 2>/dev/null || echo "")
    [ "$SYNC" = "Synced" ] && [ "$HEALTH" = "Healthy" ] && break
    if [ "$WAITED" -ge 300 ]; then
        fail "ArgoCD didn't reach Synced/Healthy within 5 minutes (last seen: sync=$SYNC health=$HEALTH). Check 'kubectl describe application devops-app -n argocd'."
    fi
    sleep 10
    WAITED=$((WAITED + 10))
done
success "ArgoCD reports the app as Synced and Healthy."

kubectl rollout status deployment/frontend-deployment -n devops-app --timeout=180s
kubectl rollout status deployment/backend-deployment -n devops-app --timeout=180s
kubectl rollout status deployment/worker-deployment -n devops-app --timeout=180s
success "All deployments are healthy."

info "Waiting for AWS to provision the Load Balancer URL (usually under a minute)..."
EXTERNAL_IP=""
while [ -z "$EXTERNAL_IP" ]; do
  sleep 5
  EXTERNAL_IP=$(kubectl get svc frontend-service -n devops-app --template="{{range .status.loadBalancer.ingress}}{{.hostname}}{{end}}")
done

ARGOCD_PASSWORD=$(kubectl get secret argocd-initial-admin-secret -n argocd -o jsonpath='{.data.password}' 2>/dev/null | base64 -d || echo "")

echo -e "\n${GREEN}${BOLD}=================================================================="
echo "  DEPLOYMENT COMPLETE"
echo -e "==================================================================${RESET}"
echo "  App URL (HTTP):   http://$EXTERNAL_IP"
echo "  App URL (HTTPS):  https://$EXTERNAL_IP  (self-signed cert - browser will warn, that's expected)"
echo "  Check pods:      kubectl get pods -n devops-app"
echo "  Check services:  kubectl get svc -n devops-app"
echo "  Tail logs:       kubectl logs -f deployment/backend-deployment -n devops-app"
echo ""
echo "  ArgoCD UI (not exposed to the internet - port-forward to reach it):"
echo "    kubectl port-forward svc/argocd-server -n argocd 8080:443"
echo "    then open https://localhost:8080  (self-signed cert, browser will warn)"
echo "    username: admin"
echo "    password: ${ARGOCD_PASSWORD}"
echo ""
echo "  Tear everything down when you're done: make k8s-teardown"
echo -e "${GREEN}${BOLD}==================================================================${RESET}"
