#!/bin/bash
set -e

# ── Friendly output helpers ──────────────────────────────────────────────
BOLD='\033[1m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; RESET='\033[0m'
step()    { echo -e "\n${BOLD}${YELLOW}==> $1${RESET}"; }
info()    { echo "    $1"; }
success() { echo -e "${GREEN}✔ $1${RESET}"; }
fail()    { echo -e "${RED}✘ $1${RESET}"; exit 1; }

echo -e "${BOLD}=================================================================="
echo "  DevOps App - Kubernetes Deployment"
echo "  This will: apply Terraform (RDS/S3/SNS), create or reuse an EKS"
echo "  cluster, build & push images, and deploy the app to Kubernetes."
echo "  Total time: ~15-25 minutes on a first run (mostly EKS cluster boot)."
echo -e "==================================================================${RESET}"

step "[0/8] Running pre-flight checks..."

info "Checking required CLI tools..."

# aws and docker are never auto-installed. aws-cli is often managed inside a
# venv/pip environment (`pip install awscli`) - auto-installing a second,
# different copy system-wide could create a confusing version conflict with
# whichever one the user actually intends to use. docker on Windows/WSL is
# normally Docker Desktop, a GUI installer this script has no safe way to drive.
for tool in aws docker; do
    command -v "$tool" >/dev/null 2>&1 \
        || fail "'$tool' is not installed or not on your PATH. Install it yourself and re-run this script."
done

install_terraform() {
    wget -qO- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg >/dev/null
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
        | sudo tee /etc/apt/sources.list.d/hashicorp.list >/dev/null
    sudo apt-get update -qq && sudo apt-get install -y terraform
}
install_kubectl() {
    local ver; ver=$(curl -L -s https://dl.k8s.io/release/stable.txt)
    curl -fsSL -o /tmp/kubectl "https://dl.k8s.io/release/${ver}/bin/linux/amd64/kubectl"
    chmod +x /tmp/kubectl
    sudo mv /tmp/kubectl /usr/local/bin/kubectl
}
install_eksctl() {
    curl -fsSL -o /tmp/eksctl.tar.gz "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz"
    tar -xzf /tmp/eksctl.tar.gz -C /tmp && rm -f /tmp/eksctl.tar.gz
    sudo mv /tmp/eksctl /usr/local/bin/eksctl
}
install_helm() {
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
}

# terraform/eksctl/kubectl/helm are plain binaries with no venv-conflict risk,
# so offering to install them is safe - but still asked one at a time, never
# silent, since each one runs real sudo commands against the system.
for tool in terraform eksctl kubectl helm; do
    command -v "$tool" >/dev/null 2>&1 && continue
    echo -e "${YELLOW}    '$tool' is not installed.${RESET}"
    set +e
    read -p "    Install it now automatically? [y/N]: " REPLY
    set -e
    if [[ "$REPLY" =~ ^[Yy]$ ]]; then
        info "Installing $tool..."
        "install_$tool"
        command -v "$tool" >/dev/null 2>&1 || fail "Automatic install of '$tool' did not succeed - install it manually and re-run."
        success "$tool installed."
    else
        fail "'$tool' is required. Install it manually and re-run this script."
    fi
done
success "terraform, eksctl, aws, kubectl, helm, docker all found."

info "Checking Docker is actually running..."
docker info >/dev/null 2>&1 \
    || fail "Docker is installed but the daemon isn't running. Start Docker Desktop (or the docker service) and try again."
success "Docker daemon is reachable."

info "Checking AWS credentials..."
export AWS_REGION="us-east-1"
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text) \
    || fail "Could not reach AWS. Run 'aws configure' first and make sure your credentials are valid."
export AWS_ACCOUNT_ID
CLUSTER_NAME="devops-cluster"
success "Authenticated to AWS account $AWS_ACCOUNT_ID."

info "Checking terraform.tfvars..."
if [ ! -f terraform/terraform.tfvars ]; then
    info "Not found - creating it now (asked once; only non-sensitive values are stored here)."
    set +e
    while true; do
        read -p "    S3 bucket name prefix (lowercase letters/numbers/hyphens, 3-63 chars): " BUCKET_NAME
        [[ "$BUCKET_NAME" =~ ^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$ ]] && break
        echo -e "${RED}    Invalid - lowercase letters, numbers, hyphens only, 3-63 characters.${RESET}"
    done
    read -p "    Email address for SNS alerts: " MY_EMAIL
    set -e
    cat <<EOF > terraform/terraform.tfvars
# Auto-generated by setup.sh - non-sensitive values only.
# db_password is handled separately and is NEVER written to this file.
# teardown.sh deletes this file automatically; setup.sh recreates it on the next run.
bucket_name = "${BUCKET_NAME}"
my_email    = "${MY_EMAIL}"
EOF
    success "terraform/terraform.tfvars created."
else
    success "terraform.tfvars already exists, reusing it."
fi
# db_password must never be persisted to disk - if an older tfvars file still has
# it (e.g. hand-edited), strip it so the fresh prompt below (via TF_VAR_db_password)
# is what actually gets used.
if grep -q '^db_password' terraform/terraform.tfvars 2>/dev/null; then
    sed -i '/^db_password/d' terraform/terraform.tfvars
    info "Removed db_password from terraform.tfvars - it's supplied securely below instead, never stored on disk."
fi

step "[1/8] Enter the database password for this run (kept in memory only, never written to disk)"
# No AWS Access Key / Secret prompt anymore - backend-sa and worker-sa get AWS
# permissions via IRSA (step 5) instead of long-lived static credentials.
set +e
while true; do
    read -s -p "    Database password (min 8 characters): " DB_PASSWORD; echo
    read -s -p "    Confirm database password: " DB_PASSWORD_CONFIRM; echo
    [ "$DB_PASSWORD" = "$DB_PASSWORD_CONFIRM" ] || { echo -e "${RED}    Passwords did not match, try again.${RESET}"; continue; }
    [ ${#DB_PASSWORD} -ge 8 ] || { echo -e "${RED}    Must be at least 8 characters (RDS requirement), try again.${RESET}"; continue; }
    break
done
set -e
export TF_VAR_db_password="$DB_PASSWORD"
success "Database password captured for this run."

step "[2/8] Applying Terraform (RDS, S3, SNS, IAM, networking)..."
cd terraform
terraform init -input=false
# -auto-approve: this script already stops (set -e) on any Terraform error,
# and re-running apply on unchanged infra is a safe no-op, so we skip the
# interactive "yes" prompt to keep the whole deploy hands-off.
terraform apply -auto-approve
VPC_ID=$(terraform output -raw vpc_id)
PUBLIC_SUBNET_IDS=$(terraform output -raw public_subnet_ids)
PRIVATE_SUBNET_IDS=$(terraform output -raw private_subnet_ids)
RDS_SG_ID=$(terraform output -raw rds_security_group_id)
RDS_ENDPOINT_FULL=$(terraform output -raw rds_endpoint)
DB_HOST=$(echo $RDS_ENDPOINT_FULL | cut -d':' -f1)
S3_BUCKET=$(terraform output -raw s3_bucket_name)
SNS_TOPIC=$(terraform output -raw sns_topic_arn)
DB_NAME=$(terraform output -raw db_name 2>/dev/null || echo "appdb")
cd ..
success "AWS infrastructure ready (RDS: $DB_HOST)."

PENDING_EMAIL=$(aws sns list-subscriptions-by-topic --topic-arn "$SNS_TOPIC" --region "$AWS_REGION" \
    --query "Subscriptions[?SubscriptionArn=='PendingConfirmation'].Endpoint" --output text 2>/dev/null || true)
if [ -n "$PENDING_EMAIL" ]; then
    echo -e "${YELLOW}    ⚠ SNS email ($PENDING_EMAIL) hasn't been confirmed yet.${RESET}"
    echo "      Check that inbox and click the confirmation link, or alert emails won't arrive"
    echo "      (the app will still work and report success either way)."
fi

step "[3/8] Ensuring EKS cluster '$CLUSTER_NAME' exists inside VPC $VPC_ID..."
if eksctl get cluster --name "$CLUSTER_NAME" --region "$AWS_REGION" >/dev/null 2>&1; then
    info "Cluster already exists, reusing it."
else
    info "Creating cluster inside the existing VPC/subnets (this takes 15-20 minutes)..."
    eksctl create cluster \
        --name "$CLUSTER_NAME" \
        --region "$AWS_REGION" \
        --vpc-public-subnets="$PUBLIC_SUBNET_IDS" \
        --vpc-private-subnets="$PRIVATE_SUBNET_IDS" \
        --nodes 2 \
        --node-type t3.small \
        --managed
fi
aws eks update-kubeconfig --name "$CLUSTER_NAME" --region "$AWS_REGION"
success "kubectl is now pointed at '$CLUSTER_NAME'."

step "[4/8] Allowing the EKS cluster to reach RDS on port 5432..."
EKS_SG_ID=$(aws eks describe-cluster --name "$CLUSTER_NAME" --region "$AWS_REGION" \
    --query 'cluster.resourcesVpcConfig.clusterSecurityGroupId' --output text)
aws ec2 authorize-security-group-ingress \
    --group-id "$RDS_SG_ID" \
    --protocol tcp --port 5432 \
    --source-group "$EKS_SG_ID" \
    --region "$AWS_REGION" 2>/dev/null && success "Firewall rule added." \
    || info "Rule already exists, skipping."

step "[5/8] Setting up IRSA so backend/worker get AWS access without static keys..."
# IRSA (IAM Roles for Service Accounts) lets a pod assume a real IAM role via a
# short-lived, auto-rotated token instead of a long-lived access key sitting in
# a Secret. It needs: (a) an OIDC identity provider associated with the cluster,
# and (b) an IAM role, trusted only by a specific Kubernetes ServiceAccount, with
# the same least-privilege S3/SNS policy Terraform already created for the old
# EC2 instances (terraform/iam.tf). frontend-sa is left alone - it never needs
# AWS access at all, so it gets no role.
# IRSA's iamserviceaccount creation needs the namespace to already exist;
# Helm creates it too later (via --create-namespace), which is a harmless
# no-op if it's already there - Helm only checks for existence, it doesn't
# try to "own" the namespace as a chart-managed resource.
kubectl create namespace devops-app --dry-run=client -o yaml | kubectl apply -f - >/dev/null

eksctl utils associate-iam-oidc-provider \
    --cluster "$CLUSTER_NAME" --region "$AWS_REGION" --approve
success "Cluster has an OIDC provider (required for IRSA)."

POLICY_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:policy/DevOps-App-Least-Privilege-Policy"
for sa in backend-sa worker-sa; do
    eksctl create iamserviceaccount \
        --cluster "$CLUSTER_NAME" --region "$AWS_REGION" \
        --namespace devops-app --name "$sa" \
        --attach-policy-arn "$POLICY_ARN" \
        --approve --override-existing-serviceaccounts
    success "$sa can now reach S3/SNS via IRSA - no AWS keys involved."
done

step "[6/8] Generating the TLS cert and the Helm values file for this run..."
# Self-signed, not from a real CA - browsers will show a "not trusted" warning.
# Getting a real trusted cert (ACM/cert-manager) needs a domain name pointed at
# the load balancer, which is out of scope here. Regenerated fresh every run
# rather than reused, since it's cheap and avoids needing to persist it anywhere.
TLS_DIR=$(mktemp -d)
openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
    -keyout "$TLS_DIR/tls.key" -out "$TLS_DIR/tls.crt" \
    -subj "/CN=devops-app/O=devops-app" 2>/dev/null
TLS_CRT_B64=$(base64 -w0 "$TLS_DIR/tls.crt")
TLS_KEY_B64=$(base64 -w0 "$TLS_DIR/tls.key")
rm -rf "$TLS_DIR"

B64_DB_PASS=$(echo -n "$DB_PASSWORD" | base64 | tr -d '\n')

# All the values that differ per run (real infra data, the password, the cert)
# live only in this temp file - never written to a tracked path, deleted the
# moment `helm upgrade` has read it.
HELM_DYNAMIC_VALUES=$(mktemp)
cat <<EOF > "$HELM_DYNAMIC_VALUES"
image:
  registry: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
config:
  dbHost: "${DB_HOST}"
  s3BucketName: "${S3_BUCKET}"
  snsTopicArn: "${SNS_TOPIC}"
secrets:
  dbPasswordB64: "${B64_DB_PASS}"
tls:
  crtB64: "${TLS_CRT_B64}"
  keyB64: "${TLS_KEY_B64}"
EOF
success "Helm values ready (TLS cert, DB endpoint, S3/SNS details, password)."

step "[7/8] Building, scanning, tagging, and pushing Docker images to ECR..."
aws ecr get-login-password --region "$AWS_REGION" | \
    docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com" >/dev/null

# Trivy is optional (bonus, not one of the hard-required tools from step 0) -
# scan if it's available, skip quietly if not.
HAVE_TRIVY=false
if command -v trivy >/dev/null 2>&1; then
    HAVE_TRIVY=true
else
    info "trivy not installed - skipping image vulnerability scanning (optional)."
    info "Install: https://aquasecurity.github.io/trivy/latest/getting-started/installation/"
fi

for service in frontend backend worker; do
    info "Processing $service..."
    docker build -q -t devops-$service ./$service

    if [ "$HAVE_TRIVY" = true ]; then
        info "Scanning devops-$service for HIGH/CRITICAL vulnerabilities..."
        # --exit-code 0: report findings but never fail the deploy over them -
        # base images like python:3.11-slim will always have some OS-level CVEs
        # that aren't practically fixable from this project alone.
        trivy image --severity HIGH,CRITICAL --quiet --exit-code 0 --table-mode summary devops-$service:latest
    fi

    docker tag devops-$service:latest "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/devops-$service:v1.0.0"
    docker push -q "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/devops-$service:v1.0.0" >/dev/null
done
success "All 3 images built, scanned, and pushed as :v1.0.0."

step "[8/8] Deploying with Helm and waiting for rollout..."
# --create-namespace: safe to pass even though the namespace already exists
# (created in step 5, for IRSA) - it only creates if missing, it never tries
# to "adopt" or manage the namespace as a chart resource.
helm upgrade --install devops-app ./helm/devops-app \
    --namespace devops-app --create-namespace \
    -f ./helm/devops-app/values.yaml \
    -f "$HELM_DYNAMIC_VALUES"
rm -f "$HELM_DYNAMIC_VALUES"
success "Helm release 'devops-app' installed/upgraded."

kubectl rollout status deployment/frontend-deployment -n devops-app --timeout=180s
kubectl rollout status deployment/backend-deployment -n devops-app --timeout=180s
kubectl rollout status deployment/worker-deployment -n devops-app --timeout=180s
success "All deployments are healthy."

info "Waiting for AWS to provision the Load Balancer URL (usually under a minute)..."
EXTERNAL_IP=""
while [ -z "$EXTERNAL_IP" ]; do
  sleep 5
  EXTERNAL_IP=$(kubectl get svc frontend-service -n devops-app --template="{{range .status.loadBalancer.ingress}}{{.hostname}}{{end}}")
done

echo -e "\n${GREEN}${BOLD}=================================================================="
echo "  DEPLOYMENT COMPLETE"
echo -e "==================================================================${RESET}"
echo "  App URL (HTTP):   http://$EXTERNAL_IP"
echo "  App URL (HTTPS):  https://$EXTERNAL_IP  (self-signed cert - browser will warn, that's expected)"
echo "  Check pods:      kubectl get pods -n devops-app"
echo "  Check services:  kubectl get svc -n devops-app"
echo "  Tail logs:       kubectl logs -f deployment/backend-deployment -n devops-app"
echo "  Tear everything down when you're done: make k8s-teardown"
echo -e "${GREEN}${BOLD}==================================================================${RESET}"
