#!/bin/bash
set -e

# Creates or updates ci-application and cd-application via Jenkins' REST
# API. Idempotent - safe to re-run after editing the config.xml files or
# the Jenkinsfiles they point at. Deliberately NOT run during Jenkins' own
# boot sequence (see jenkins/values.yaml): this only touches an
# already-running controller, so a mistake here fails just this script,
# not Jenkins itself.
#
# Requires: kubectl pointed at the cluster, and a port-forward to Jenkins
# already running in another terminal:
#   kubectl port-forward svc/jenkins -n jenkins 8080:8080

JENKINS_URL="${JENKINS_URL:-http://localhost:8080}"
JENKINS_USER="admin"
# MSYS_NO_PATHCONV=1: no-op outside Windows Git Bash - see configure-jenkins.sh
# for why it's needed there (MSYS mangles the /bin/cat path argument).
JENKINS_PASSWORD=$(MSYS_NO_PATHCONV=1 kubectl exec --namespace jenkins svc/jenkins -c jenkins -- \
    /bin/cat /run/secrets/additional/chart-admin-password | tr -d '\r')

# Jenkins ties the CSRF crumb to the session that issued it. Fetching it
# and using it in two separate curl calls (each starting its own fresh
# Basic Auth session, no cookie continuity) invalidates it by the second
# request: "403 No valid crumb was included in the request". A shared
# cookie jar keeps both calls in the same session.
JAR=$(mktemp)
trap 'rm -f "$JAR"' EXIT

CRUMB=$(curl -sf -c "$JAR" -b "$JAR" -u "${JENKINS_USER}:${JENKINS_PASSWORD}" \
    "${JENKINS_URL}/crumbIssuer/api/json" \
    | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['crumbRequestField']+':'+d['crumb'])")

create_or_update_job() {
    local job_name="$1"
    local config_file="$2"
    local status
    status=$(curl -s -c "$JAR" -b "$JAR" -o /dev/null -w '%{http_code}' \
        -u "${JENKINS_USER}:${JENKINS_PASSWORD}" \
        "${JENKINS_URL}/job/${job_name}/api/json")

    if [ "$status" = "200" ]; then
        echo "Updating existing job: ${job_name}"
        curl -sf -c "$JAR" -b "$JAR" -u "${JENKINS_USER}:${JENKINS_PASSWORD}" -H "${CRUMB}" \
            -H "Content-Type: application/xml" \
            --data-binary "@${config_file}" \
            "${JENKINS_URL}/job/${job_name}/config.xml"
    else
        echo "Creating job: ${job_name}"
        curl -sf -c "$JAR" -b "$JAR" -u "${JENKINS_USER}:${JENKINS_PASSWORD}" -H "${CRUMB}" \
            -H "Content-Type: application/xml" \
            --data-binary "@${config_file}" \
            "${JENKINS_URL}/createItem?name=${job_name}"
    fi
    echo ""
}

create_or_update_job "ci-application" "jenkins/jobs/ci-application-config.xml"
create_or_update_job "cd-application" "jenkins/jobs/cd-application-config.xml"

# ci-application-pr-config.xml carries a placeholder, not the real webhook
# token (see that file's own comment) - substituted into a throwaway temp
# copy here, so the real value (generated by configure-jenkins.sh, read
# straight from the live git-webhook-secret Secret) is never written back
# into the git-tracked XML.
PR_TOKEN=$(MSYS_NO_PATHCONV=1 kubectl get secret git-webhook-secret -n jenkins \
    -o jsonpath='{.data.pr-token}' | base64 -d) \
    || { echo "Couldn't read git-webhook-secret's pr-token key - run configure-jenkins.sh first."; exit 1; }
PR_CONFIG_TMP=$(mktemp)
# Replaces the single EXIT trap set above (JAR) rather than adding a second
# one - bash only keeps the most recently registered EXIT trap, not a stack
# of them, so both temp files are cleaned up from this one line.
trap 'rm -f "$JAR" "$PR_CONFIG_TMP"' EXIT
sed "s/__PR_WEBHOOK_TOKEN__/${PR_TOKEN}/" "jenkins/jobs/ci-application-pr-config.xml" > "$PR_CONFIG_TMP"
create_or_update_job "ci-application-pr" "$PR_CONFIG_TMP"

echo "Done. Verify:"
echo "  curl -s -u ${JENKINS_USER}:\$JENKINS_PASSWORD ${JENKINS_URL}/job/ci-application/api/json | head -c 300"
echo "  curl -s -u ${JENKINS_USER}:\$JENKINS_PASSWORD ${JENKINS_URL}/job/cd-application/api/json | head -c 300"
echo "  curl -s -u ${JENKINS_USER}:\$JENKINS_PASSWORD ${JENKINS_URL}/job/ci-application-pr/api/json | head -c 300"
