---
# tasks file for common
- name: Update apt cache and install base dependencies
  apt:
    name:
      - python3-pip
      - python3-venv
      - git
    state: present
    update_cache: yes

- name: Create the main application directory
  file:
    path: /home/ubuntu/app
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'