---
# This is an example secrets file. 
# Do NOT commit your actual secrets.yml to version control!
# Copy this file locally to secrets.yml and encrypt it using ansible-vault.

db_password: "YOUR_SECURE_DB_PASSWORD"
api_key: "YOUR_DUMMY_API_KEY"